name = "curisdata-site"
compatibility_date = "2026-04-16"
pages_build_output_dir = "."

[vars]
SITE_NAME = "CurisData"

[[r2_buckets]]
binding = "REPORT_DATA_BUCKET"
bucket_name = "demographic-files"
preview_bucket_name = "demographic-files"
